
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null


  - name: acad_car_tbl

  - name: class_attribute

  - name: crse_component

  - name: crse_topics
  
  - name: stdnt_cohort

  
  - name: stg_acad_prog_tbl

  - name: stg_academic_careers

  - name: stg_academic_groups
  
  - name: stg_acadeimc_organizations

  - name: stg_cip_codes

  
  - name: stg_ethnic


  - name: stg_first_gen_ug_stdnt_ind


  - name: stg_first_last_term_attended


  - name: stg_est_gross_fam_inc_des

  - name: stg_hegis_codes
 
 
  - name: personal_data



