sources:
  - name: cs
    database: raw
    schema: csprod
    tables:
      - name: ps_acad_car_tbl
      - name: ps_acad_degr
      - name: ps_acad_degr_hons
      - name: ps_acad_degr_plan
      - name: ps_acad_degr_spln
      - name: ps_acad_group_tbl
      - name: ps_acad_org_tbl
      - name: ps_acad_plan
      - name: ps_acad_plan_owner
      - name: ps_acad_plan_tbl
      - name: ps_acad_prog
      - name: ps_acad_prog_tbl
      - name: ps_acad_stactn_tbl
      - name: ps_acad_stdng_actn
      - name: ps_acad_subplan
      - name: ps_acad_subpln_tbl
      - name: ps_addresses
      - name: ps_adj_code_trm_vw
    
      - name: ps_adm_appl_cmp
      - name: ps_adm_appl_data

      - name: ps_adm_appl_eval
      - name: ps_adm_appl_prog
      - name: ps_adm_functn_tbl
      - name: ps_admit_type_tbl
      - name: ps_campus_tbl
      - name: ps_cip_code_tbl
      - name: ps_class_assoc
      - name: ps_class_attribute
      - name: ps_class_component
      - name: ps_class_exam
      - name: ps_class_instr
      - name: ps_class_mtg_pat
      - name: ps_class_rsrv_cap
      - name: ps_class_rsrv_grp
      - name: ps_class_tbl
      - name: ps_comm_catg_tbl
      - name: ps_comm_ctxt_tbl
      - name: ps_committee
      - name: ps_committee_membr
      - name: ps_committee_tbl
      - name: ps_communication
      - name: ps_country_tbl
      - name: ps_crse_attr_tbl
      - name: ps_crse_attr_value
      - name: ps_crse_attributes
      - name: ps_crse_catalog
      - name: ps_crse_component
      - name: ps_crse_offer
      - name: ps_crse_offer_ownr
      - name: ps_crse_topics
      - name: ps_cs_chklst_3cgrp
      - name: ps_cs_chklst_tbl
      - name: ps_degr_honors_tbl
      - name: ps_degree_tbl
      - name: ps_dept_tbl
      - name: ps_enrl_req_detail
      - name: ps_ethnic_grp_tbl
      - name: ps_ext_course
      - name: ps_ext_org_tbl
      - name: ps_ext_org_tbl_adm
      - name: ps_facility_tbl
      - name: ps_hegis_code_tbl
      - name: ps_instruct_mode
      - name: ps_item_sf
      - name: ps_location_tbl
      - name: ps_ls_schl_typ_tbl
      - name: ps_m_cc_comm_tbl
      - name: ps_m_cc_eth_rpt_vw
      - name: ps_m_cc_ordrnam_vw
      - name: ps_m_he_acdprg_caf
      - name: ps_m_sr_acdpln_caf
      - name: ps_m_sr_classtblvw
      - name: ps_m_sr_cohort
      - name: ps_m_sr_exam_score
      - name: ps_m_sr_exam_stats
      - name: ps_m_sr_gc_request
      - name: ps_m_sr_gc_rsn_tbl
      - name: ps_m_sr_plcrcm_tbl
      - name: ps_m_sr_plctst_tbl
      - name: ps_m_sr_ss_proxy
      - name: ps_m_sr_stdnt_lres
      - name: ps_m_sr_stu_engl
      - name: ps_m_sr_stu_plc_hd
      - name: ps_m_sr_stu_plcmnt
      - name: ps_m_sr_ta_tuitat
      - name: ps_mlstn_atmpt      
      - name: ps_name_prefix_tbl
      - name: ps_org_contact
      - name: ps_org_dept
      - name: ps_org_location
      - name: ps_person
      - name: ps_person_checklst
      - name: ps_person_chk_item
      - name: ps_personal_data
      - name: ps_personal_phone
      - name: ps_prog_rsn_tbl
      - name: ps_rating_val_tbl
      - name: ps_repeat_code_tbl
      - name: ps_rq_grp_tbl
      - name: ps_rq_line_tbl
      - name: ps_rq_main_tbl
      - name: ps_rqmnt_desig_tbl
      - name: ps_sa_tcmp_rel_tbl
      - name: ps_sa_test_tbl
      - name: ps_saa_adb_conduse
      - name: ps_saa_adb_courses
      - name: ps_saa_adb_crseavl
      - name: ps_saa_adb_crseuse
      - name: ps_saa_adb_report
      - name: ps_saa_adb_results
      - name: ps_saa_adb_whatif
      - name: ps_scc_cklsitm_tbl
      - name: ps_scc_lov_adhoc
      - name: ps_scc_org_typ_tbl
      - name: ps_sctn_cmbnd
      - name: ps_sctn_cmbnd_tbl
      - name: ps_session_tbl
      - name: ps_ssr_crse_typoff
      - name: ps_state_tbl
      - name: ps_stdnt_advr_hist
      - name: ps_stdnt_car_mlstn
      - name: ps_stdnt_car_term
      - name: ps_stdnt_career
      - name: ps_stdnt_enrl
      - name: ps_stdnt_incomplte
      - name: ps_stdnt_plcmnt
      - name: ps_stdnt_plcmnt_engl
      - name: ps_stdnt_plcmnt_hdr
      - name: ps_stdnt_test_comp
      - name: ps_study_field_tbl
      - name: ps_subject_tbl
      - name: ps_term_tbl
      - name: ps_term_val_tbl
      - name: ps_trns_crse_dtl
      - name: ps_trns_crse_sch
      - name: ps_trns_crse_term
      - name: ps_trns_othr_dtl
      - name: ps_trns_othr_model
      - name: ps_trns_othr_term
      - name: ps_trns_test_dtl
      - name: ps_trns_test_model
      - name: ps_trns_test_term
      - name: ps_var_data_sprg
      - name: ps_var_data_strm
      - name: psxlatitem
      - name: ps_divers_ethnic
      - name: ps_ethnicity_dtl